kind: Service
apiVersion: v1
metadata:
  name: code-with-quarkus
  labels:
    app: code-with-quarkus
  annotations:
spec:
  ports:
    - name: http-8080
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: code-with-quarkus
